export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  STAFF = 'STAFF',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  SUPER_ADMIN = 'SUPER_ADMIN',
  VIEWER = 'VIEWER',
}

export enum AccountStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
  PENDING_ACTIVATION = 'PENDING_ACTIVATION',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  QUEUED = 'QUEUED',
  IN_PROGRESS = 'IN_PROGRESS',
  QUALITY_CHECK = 'QUALITY_CHECK',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  CUSTOMER_REFUSED_DIVR = 'CUSTOMER_REFUSED_DIVR',
}

export enum ServiceType {
  WASH = 'WASH',
  POLISH = 'POLISH',
  DETAILING = 'DETAILING',
  COMBO = 'COMBO',
  ADD_ON = 'ADD_ON',
}

export enum PaymentMethod {
  STRIPE = 'STRIPE',
  PAYPAL = 'PAYPAL',
  CASH = 'CASH',
  LOYALTY_POINTS = 'LOYALTY_POINTS',
  SPLIT = 'SPLIT',
  SUBSCRIPTION = 'SUBSCRIPTION',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
}

export enum OtpPurpose {
  REGISTRATION = 'REGISTRATION',
  LOGIN = 'LOGIN',
  PASSWORD_RESET = 'PASSWORD_RESET',
  MFA = 'MFA',
  PHONE_CHANGE = 'PHONE_CHANGE',
  EMAIL_CHANGE = 'EMAIL_CHANGE',
}

export enum LoyaltyTransactionType {
  EARNED = 'EARNED',
  REDEEMED = 'REDEEMED',
  EXPIRED = 'EXPIRED',
  BONUS = 'BONUS',
  REVERSED = 'REVERSED',
  ADJUSTED = 'ADJUSTED',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
}