export enum PaymentMethod {
  CARD = 'CARD',
  CASH = 'CASH',
}

export enum DisputeReason {
  WORK_NOT_COMPLETED = 'WORK_NOT_COMPLETED',
  WORK_POOR_QUALITY = 'WORK_POOR_QUALITY',
  OVERCHARGED = 'OVERCHARGED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  OTHER = 'OTHER',
}

export enum DesiredOutcome {
  FULL_REFUND = 'FULL_REFUND',
  PARTIAL_REFUND = 'PARTIAL_REFUND',
  REDO_SERVICE = 'REDO_SERVICE',
}

export enum PayoutStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}

export const PAYMENT_STATUS_CONTEXTS = {
  PAID: 'PAID',
  PENDING: 'PAYMENT_PENDING',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PAYOUT_PENDING: 'PAYOUT_PENDING',
  CONFIRMED: 'CONFIRMED',
};

export const MIN_STRIPE_AMOUNT_EGP = 30;
export const MIN_LOYALTY_POINTS = 100;
export const DEFAULT_CURRENCY = 'EGP';
export const DEFAULT_PLATFORM_FEE_PCT = 10;

export const NOTIFICATION_CODES = {
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYOUT_PROCESSED: 'PAYOUT_PROCESSED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  DISPUTE_CREATED: 'DISPUTE_CREATED',
};
